"""freeze_env.py — record what the numbers in this repo were actually measured on.

WHY
---
Review finding P2-2: `requirements.txt` / `requirements-ml.txt` carry only `>=`
bounds, so a fresh install a year from now resolves a different stack than the one
every figure in SCOREBOARD.md was measured against. ML_PRACTICES already records
that CPU vs GPU can flip a near-threshold detection; an unpinned library stack is
the same hazard by a second route.

Deliberately RECORDS rather than pins. Hard-pinning a scientific-python stack on
one Windows box is a good way to make `pip install` fail for the next person; a
recorded resolution costs nothing and answers "what was this measured on".

It also surfaces the thing that motivated the file: the two venvs that both
produce published numbers are NOT the same stack (opencv differs by a MAJOR
version), so a .venv figure and a .venv-train figure differ by device *and* by
libraries, and no experiment here has separated the two.

    py tools/freeze_env.py            # rewrite backend/requirements-resolved.txt
    py tools/freeze_env.py --check    # exit 1 if it is out of date (for CI)
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "backend" / "requirements-resolved.txt"

#: The packages whose version can plausibly change a NUMBER, not just an API.
PACKAGES = ("numpy", "scipy", "opencv-python", "imageio-ffmpeg",
            "torch", "torchvision", "ultralytics", "gdown")

VENVS = (("backend/.venv", "CPU - tests, eval, cached-perception re-runs"),
         ("backend/.venv-train", "CUDA - training and GPU perception passes"))

HEADER = """\
# Resolved environment - what the numbers in this repo were actually measured on
#
# GENERATED by tools/freeze_env.py - do not hand-edit; rerun the tool.
#
# WHY THIS FILE EXISTS (review finding P2-2)
# requirements*.txt use only >= bounds, so `pip install -r` a year from now
# resolves a different stack than the one every figure in SCOREBOARD.md was
# measured on. ML_PRACTICES already records that CPU vs GPU can flip a
# near-threshold detection; an unpinned library stack is the same hazard by a
# second route. This RECORDS rather than pins: hard-pinning this stack is a good
# way to break a fresh install, and "what was it measured on" is the question
# that actually needed answering.
#
# THE DIVERGENCE THIS EXPOSED, which nothing had recorded: the two venvs that
# both produce published numbers are not the same stack - they differ in opencv
# MAJOR version on top of the intended cpu/cuda split - so a .venv number and a
# .venv-train number differ by device AND by libraries, and no experiment in this
# repo has separated the two.
"""


def versions(venv: str) -> dict[str, str]:
    py = REPO / venv / "Scripts" / "python.exe"
    if not py.exists():                       # POSIX layout, for portability
        py = REPO / venv / "bin" / "python"
    if not py.exists():
        return {}
    code = ("import importlib.metadata as m\n"
            "import sys\n"
            f"pkgs = {PACKAGES!r}\n"
            "for p in pkgs:\n"
            "    try: print(p + '==' + m.version(p))\n"
            "    except Exception: pass\n"
            "print('python==' + sys.version.split()[0])\n")
    r = subprocess.run([str(py), "-c", code], capture_output=True, text=True)
    out = {}
    for line in r.stdout.splitlines():
        if "==" in line:
            k, v = line.split("==", 1)
            out[k] = v
    return out


def render() -> str:
    lines = [HEADER]
    for venv, why in VENVS:
        got = versions(venv)
        lines.append(f"[{venv}]  # {why}")
        if not got:
            lines.append("# (not present on this machine)")
        for k, v in got.items():
            lines.append(f"{k}=={v}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale, and say what moved")
    args = ap.parse_args()
    fresh = render()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have.strip() != fresh.strip():
            print(f"STALE: {OUT.relative_to(REPO)} does not match this machine.")
            print("Rerun `py tools/freeze_env.py`. Note a mismatch is not "
                  "automatically wrong - it means numbers measured here were "
                  "measured on a different stack than the file claims.")
            sys.exit(1)
        print("up to date")
        return
    OUT.write_text(fresh, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
